#ifndef PVTPACKAGE_ENUMS_HPP
#define PVTPACKAGE_ENUMS_HPP

#include "MultiphaseSystem/PVTEnums.hpp"

#include <nlohmann/json.hpp>

namespace PVTPackage
{

NLOHMANN_JSON_SERIALIZE_ENUM( PHASE_STATE, {
  { PHASE_STATE::UNKNOWN, "UNKNOWN" },
  { PHASE_STATE::GAS, "GAS" },
  { PHASE_STATE::OIL, "OIL" },
  { PHASE_STATE::WATER, "WATER" },
  { PHASE_STATE::OIL_GAS, "OIL_GAS" },
  { PHASE_STATE::GAS_WATER, "GAS_WATER" },
  { PHASE_STATE::OIL_WATER, "OIL_WATER" },
  { PHASE_STATE::OIL_GAS_WATER, "OIL_GAS_WATER" }
} )

NLOHMANN_JSON_SERIALIZE_ENUM( PHASE_TYPE, {
  { PHASE_TYPE::UNKNOWN, "UNKNOWN" },
  { PHASE_TYPE::LIQUID_WATER_RICH, "LIQUID_WATER_RICH" },
  { PHASE_TYPE::OIL, "OIL" },
  { PHASE_TYPE::GAS, "GAS" }
} )

NLOHMANN_JSON_SERIALIZE_ENUM( EOS_TYPE, {
  { EOS_TYPE::UNKNOWN, "UNKNOWN" },
  { EOS_TYPE::REDLICH_KWONG_SOAVE, "REDLICH_KWONG_SOAVE" },
  { EOS_TYPE::PENG_ROBINSON, "PENG_ROBINSON" }
} )

}

#endif //PVTPACKAGE_ENUMS_HPP
