#ifndef PVTPACKAGE_ENUMS_HPP
#define PVTPACKAGE_ENUMS_HPP

#include "refactor/JsonKeys.hpp"

#include "MultiphaseSystem/PVTEnums.hpp"

#include <nlohmann/json.hpp>

namespace PVTPackage
{

NLOHMANN_JSON_SERIALIZE_ENUM( PHASE_STATE, {
  { PHASE_STATE::UNKNOWN, EnumKeys::PHASE_STATE_UNKNOWN },
  { PHASE_STATE::GAS, EnumKeys::PHASE_STATE_GAS },
  { PHASE_STATE::OIL, EnumKeys::PHASE_STATE_OIL },
  { PHASE_STATE::WATER, EnumKeys::PHASE_STATE_WATER },
  { PHASE_STATE::OIL_GAS, EnumKeys::PHASE_STATE_OIL_GAS },
  { PHASE_STATE::GAS_WATER, EnumKeys::PHASE_STATE_GAS_WATER },
  { PHASE_STATE::OIL_WATER, EnumKeys::PHASE_STATE_OIL_WATER },
  { PHASE_STATE::OIL_GAS_WATER, EnumKeys::PHASE_STATE_OIL_GAS_WATER }
} )

NLOHMANN_JSON_SERIALIZE_ENUM( PHASE_TYPE, {
  { PHASE_TYPE::UNKNOWN, EnumKeys::PHASE_TYPE_UNKNOWN },
  { PHASE_TYPE::LIQUID_WATER_RICH, EnumKeys::PHASE_TYPE_LIQUID_WATER_RICH },
  { PHASE_TYPE::OIL, EnumKeys::PHASE_TYPE_OIL },
  { PHASE_TYPE::GAS, EnumKeys::PHASE_TYPE_GAS }
} )

NLOHMANN_JSON_SERIALIZE_ENUM( EOS_TYPE, {
  { EOS_TYPE::UNKNOWN, EnumKeys::EOS_TYPE_UNKNOWN },
  { EOS_TYPE::REDLICH_KWONG_SOAVE, EnumKeys::EOS_TYPE_REDLICH_KWONG_SOAVE },
  { EOS_TYPE::PENG_ROBINSON, EnumKeys::EOS_TYPE_PENG_ROBINSON }
} )

} // end of namespace PVTPackage

#endif //PVTPACKAGE_ENUMS_HPP
